[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
framework = arduino
monitor_speed = 115200

; Ethernet settings for WT32-ETH01 V1.4
build_flags =
    -D ETH_PHY_ADDR=1
    -D ETH_PHY_TYPE=ETH_PHY_LAN8720
    -D ETH_PHY_POWER=16
    -D ETH_PHY_MDC=23
    -D ETH_PHY_MDIO=18
    -D ETH_CLK_MODE=ETH_CLOCK_GPIO0_IN

; OTA upload (uncomment and set IP when needed)
; upload_protocol = espota
; upload_port = 192.168.1.xxx

; Disable WiFi and Bluetooth
build_unflags =
    -DBOARD_HAS_PSRAM
